name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: meuse
          POSTGRES_USER: meuse
          POSTGRES_DB: meuse

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Create folders specified in default config
      run: |
        mkdir registry
        mkdir crates

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test
